version: 2.1

orbs:
  python: circleci/python@1.3.3

jobs:
  test: 
    docker:
      - image: cimg/base:2020.01
    steps:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: unittest

workflows:
  test-build-push-image:
    jobs:
      - test
