version: 2.1

orbs:
  python: circleci/python@1.3.3

jobs:
  test: 
    executor: python/default
    steps:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: unittest

workflows:
  test-build-push-image:
    jobs:
      - test
