version: 2.1

jobs:
  dockerbuild:
    steps:
      - run: docker build -t devops-bookstore-api:${CIRCLE_BUILD_NUM} .

orbs:
  python: circleci/python@1.3.3
workflows:
  main:
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: unittest
      - dockerbuild
