version: 2.1

orbs:
  python: circleci/python@1.3.3

jobs:
  docker-build: 
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
          docker_layer_caching: true
      - run: |
          TAG=1.$CIRCLE_BUILD_NUM
          docker build -t devops-bookstore-api:$TAG .
      

workflows:
  test-build-push-image:
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: unittest 
      - docker-build
